config/routes.rb
Rails.application.routes.draw do

  root to: 'users#index'

  devise_for :users, controllers: {
    sessions: 'users/sessions',
    registrations: 'users/registrations',
    passwords: 'users/passwords',
    confirmations: 'users/confirmations'
  }

  resources :loan_requests, only: [:new, :create, :show] do
    member do
      patch :approve
      patch :reject
      patch :adjust
      patch :repay
    end
  end

  resources :users
  get 'dashboard', to: 'users#dashboard'
end

app/models/loan_request.rb
class LoanRequest < ApplicationRecord
	belongs_to :user

	enum state: %i[ requested approved processing closed rejected waiting_for_adjustment_acceptance readjustment_requested ], _prefix: true

  def total_amount
    amount + interest_amount
  end

  def repaid?
    state == 'closed'
  end
end

app/controllers/loan_requests_controller.rb
class LoanRequestsController < ApplicationController
  before_action :authenticate_user!
  before_action :set_loan_request, only: [:approve, :reject, :adjust, :repay, :show]
  before_action :check_admin, except: [:create, :new, :show, :repay]

  def show
  end

  def new
    @loan_request = LoanRequest.new
  end

  def create
    @loan_request = current_user.loan_requests.new(loan_request_params)
    if @loan_request.save
      redirect_to dashboard_path, notice: 'Loan request created successfully.'
    else
      render :new
    end
  end

  def approve
    service = LoanRequestService.new(@loan_request, current_user)
    if service.approve
      redirect_to dashboard_path, notice: 'Loan request approved.'
    else
      redirect_to dashboard_path, alert: 'Loan approval failed.'
    end
  end

  def reject
    service = LoanRequestService.new(@loan_request, current_user)
    if service.reject
      redirect_to dashboard_path, notice: 'Loan request rejected.'
    else
      redirect_to dashboard_path, alert: 'Loan rejection failed.'
    end
  end

  def adjust
    service = LoanRequestService.new(@loan_request, current_user)
    if service.adjust(loan_request_params)
      redirect_to dashboard_path, notice: 'Loan request adjusted successfully.'
    else
      redirect_to dashboard_path, alert: 'Failed to adjust loan request.'
    end
  end

  def repay
    pay_amount = params['loan_request']['amount'].to_i
    service = LoanRequestService.new(@loan_request, current_user)
    if service.repay(pay_amount)
      redirect_to dashboard_path, notice: 'Repayment successful.'
    else
      redirect_to dashboard_path, alert: 'Repayment failed.'
    end
  end

  private

  def set_loan_request
    @loan_request = LoanRequest.find(params[:id])
  end

  def check_admin
    render json: {msg: "You are not authorized to perform this action"} unless current_user.is_admin
  end

  def loan_request_params
    params.permit(:amount, :rate_of_interest)
  end
end

app/helpers/loan_requests_helper.rb
module LoanRequestsHelper
end

app/views/loan_requests/new.html.erb
<div class="flex items-center justify-center min-h-screen px-4 text-center">
  <div id="loan-request-modal" class="fixed inset-0 flex items-center justify-center bg-black bg-opacity-50 z-50 hidden">
    <div class="bg-white text-black rounded-lg shadow-lg p-6 w-full max-w-md">
      <h3 class="text-xl font-bold mb-4">Request Loan</h3>
      <if current_user>
      <%= form_with model: @loan_request, url: loan_requests_path, local: true, class: 'space-y-4' do |form| %>
        <div>
          <%= form.label :amount, 'Amount', class: 'block text-sm font-medium text-gray-700' %>
          <%= form.number_field :amount, class: 'mt-1 block w-full border border-gray-300 rounded-md shadow-sm' %>
        </div>
        <div>
          <%= form.label :rate_of_interest, 'Rate of Interest (%)', class: 'block text-sm font-medium text-gray-700' %>
          <%= form.number_field :rate_of_interest, step: 0.01, class: 'mt-1 block w-full border border-gray-300 rounded-md shadow-sm' %>
        </div>
        <div>
          <%= form.submit 'Submit Request', id: "submit-loan", class: 'bg-blue-500 text-white font-semibold py-2 px-4 rounded hover:bg-blue-600' %>
        </div>
      <% end %>
      < else >
            <%= form_with model: @loan_request, url: loan_requests_path, local: true, class: 'space-y-4' do |form| %>
        <div>
          <%= form.label :amount, 'Amount', class: 'block text-sm font-medium text-gray-700' %>
          <%= form.number_field :amount, class: 'mt-1 block w-full border border-gray-300 rounded-md shadow-sm' %>
        </div>
        <div>
          <%= form.label :rate_of_interest, 'Rate of Interest (%)', class: 'block text-sm font-medium text-gray-700' %>
          <%= form.number_field :rate_of_interest, step: 0.01, class: 'mt-1 block w-full border border-gray-300 rounded-md shadow-sm' %>
        </div>
        <div>
          <%= form.submit 'Submit Request', id: "submit-loan", class: 'bg-blue-500 text-white font-semibold py-2 px-4 rounded hover:bg-blue-600' %>
        </div>
      <% end %>

    </div>
  </div>
</div>

<script>
document.addEventListener("DOMContentLoaded", function() {
  let modal = document.getElementById("loan-request-modal");
  let loanRequestButton = document.getElementById("loan-rq");

  loanRequestButton.onclick = function() {
    modal.classList.remove("hidden");
  };

  document.getElementById("submit-loan").onclick = function() {
    modal.classList.add("hidden");
  };

  function toggleModal() {
    modal.classList.toggle("hidden");
  }
});
</script>

app/views/loan_requests/show.html.erb
<%= javascript_importmap_tags %>
<div class="min-h-screen bg-[#E1C2AD] py-10 px-6">
  <h1 class="text-2xl font-bold text-center">Loan Details</h1></br>
    <table class="min-w-full border-collapse border border-gray-300 bg-black text-white">
      <thead>
        <tr class="bg-gray-800 text-white">
          <th class="border border-gray-300 px-4 py-2">Principal Amount</th>
          <th class="border border-gray-300 px-4 py-2">Interest Amount</th>
          <th class="border border-gray-300 px-4 py-2">Total Amount to Repay</th>
          <th class="border border-gray-300 px-4 py-2">Action</th>
        </tr>
      </thead>
      <tbody>
        <tr>
          <td class="border border-gray-300 px-4 py-2"><%= @loan_request.amount %></td>
          <td class="border border-gray-300 px-4 py-2"><%= @loan_request.interest_amount %></td>
          <td class="border border-gray-300 px-4 py-2"><%= @loan_request.total_amount %></td>
          <td class="border border-gray-300 px-4 py-2">
            <% if @loan_request.state == 'approved' %>
              <%= link_to 'pay_loan', '#', id: 'pay-loan', data: { turbo_method: :patch }, class: 'bg-blue-700 text-white font-semibold py-2 px-4 rounded hover:bg-blue-800 mb-4'%>
            <% end %>
          </td>
        </tr>
      </tbody>
    </table>

  <div class="flex items-center justify-center min-h-screen px-4 text-center">
    <div id="loan-repay-modal" class="fixed inset-0 flex items-center justify-center bg-black bg-opacity-50 z-50 hidden">
      <div class="bg-white text-black rounded-lg shadow-lg p-6 w-full max-w-md">
        <h3 class="text-xl font-bold mb-4">Repay Loan</h3>
        <%= form_with model: @loan_request, url: repay_loan_request_path(@loan_request), remote: true, class: 'space-y-4' do |form| %>
          <div>
            <%= form.label :total_amount, 'Amount', class: 'block text-sm font-medium text-gray-700' %>
            <%= form.number_field :amount, value: @loan_request.total_amount, class: 'mt-1 block w-full border border-gray-300 rounded-md shadow-sm' %>
          </div>
          <div class="flex justify-end space-x-2">
            <button type="button" id="cancel", class="bg-red-500 text-white font-semibold py-2 px-4 rounded hover:bg-red-600 mr-2">Cancel</button>
            <%= form.submit 'Pay', id: 'repay-loan', class: 'bg-blue-500 text-white font-semibold py-2 px-4 rounded hover:bg-blue-600' %>
          </div>
        <%end%>
      </div>
    </div>
  </div>
</div>